version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: yarn dev
    volumes:
      - .:/home/app/supreme-api
